"""Base Agent class for VeriFlow-Agent.

This module defines the abstract base class that all pipeline stage agents
must inherit from. It provides common functionality for:
- LLM invocation (supporting multiple backends)
- Input/output validation
- Error handling and retry logic
- Metrics collection
"""

from __future__ import annotations

import json
import os
import subprocess
from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from pathlib import Path
from typing import TYPE_CHECKING, Any, Optional, Union

if TYPE_CHECKING:
    from langchain_core.language_models import BaseLanguageModel


@dataclass
class AgentResult:
    """Standardized result format for all agent executions.

    This dataclass ensures consistent output structure across all pipeline stages,
    making it easy to handle results uniformly in the graph state machine.

    Attributes:
        success: Whether the stage completed successfully
        stage: Name of the stage (e.g., "architect", "coder")
        artifacts: List of file paths generated by this stage
        metrics: Key performance indicators (e.g., token count, time taken)
        errors: List of error messages if stage failed
        warnings: List of non-fatal warning messages
        raw_output: Raw LLM output for debugging
        metadata: Additional stage-specific data
    """

    success: bool
    stage: str
    artifacts: list[str] = field(default_factory=list)
    metrics: dict[str, Any] = field(default_factory=dict)
    errors: list[str] = field(default_factory=list)
    warnings: list[str] = field(default_factory=list)
    raw_output: str = ""
    metadata: dict[str, Any] = field(default_factory=dict)

    def to_dict(self) -> dict[str, Any]:
        """Convert to dictionary for serialization (e.g., JSON checkpoint)."""
        return {
            "success": self.success,
            "stage": self.stage,
            "artifacts": self.artifacts,
            "metrics": self.metrics,
            "errors": self.errors,
            "warnings": self.warnings,
            "raw_output": self.raw_output,
            "metadata": self.metadata,
        }

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> "AgentResult":
        """Create from dictionary (e.g., when loading checkpoint)."""
        return cls(
            success=data.get("success", False),
            stage=data.get("stage", ""),
            artifacts=data.get("artifacts", []),
            metrics=data.get("metrics", {}),
            errors=data.get("errors", []),
            warnings=data.get("warnings", []),
            raw_output=data.get("raw_output", ""),
            metadata=data.get("metadata", {}),
        )


class AgentError(Exception):
    """Base exception for agent-related errors."""

    def __init__(self, message: str, stage: str = "", details: dict | None = None):
        super().__init__(message)
        self.stage = stage
        self.details = details or {}


class InputValidationError(AgentError):
    """Raised when input validation fails."""

    pass


class OutputValidationError(AgentError):
    """Raised when output validation fails."""

    pass


class LLMInvocationError(AgentError):
    """Raised when LLM invocation fails."""

    pass


class BaseAgent(ABC):
    """Abstract base class for all VeriFlow pipeline stage agents.

    This class provides the common infrastructure that all agents need:
    - LLM invocation with multiple backend support
    - Input/output file validation
    - Structured error handling
    - Metrics collection

    Subclasses must implement the `execute` method to define their specific logic.

    Example:
        ```python
        class MyAgent(BaseAgent):
            def __init__(self):
                super().__init__(
                    name="my_agent",
                    prompt_file="stage_my.md",
                    required_inputs=["workspace/docs/spec.json"],
                    output_artifacts=["workspace/rtl/output.v"]
                )

            def execute(self, context):
                # Implementation here
                pass
        ```
    """

    def __init__(
        self,
        name: str,
        prompt_file: str,
        required_inputs: list[str] | None = None,
        output_artifacts: list[str] | None = None,
        max_retries: int = 3,
        llm_backend: str = "claude_cli",  # or "anthropic", "langchain"
    ):
        """Initialize the agent.

        Args:
            name: Unique identifier for this agent (e.g., "architect", "coder")
            prompt_file: Name of the prompt file in prompts/ directory
            required_inputs: List of input file paths (relative to project_dir)
            output_artifacts: List of expected output file patterns
            max_retries: Maximum number of retry attempts on failure
            llm_backend: Which LLM invocation method to use
        """
        self.name = name
        self.prompt_file = prompt_file
        self.required_inputs = required_inputs or []
        self.output_artifacts = output_artifacts or []
        self.max_retries = max_retries
        self.llm_backend = llm_backend

        # Configurable LLM client (initialized on first use)
        self._llm_client: Any | None = None

    @abstractmethod
    def execute(self, context: dict[str, Any]) -> AgentResult:
        """Execute the agent's main logic.

        This is the main entry point that subclasses must implement.
        It should:
        1. Validate inputs using `validate_inputs()`
        2. Perform the stage's core logic
        3. Validate outputs using `validate_outputs()`
        4. Return a properly structured AgentResult

        Args:
            context: Dictionary containing:
                - project_dir: Path to project root
                - inputs: Stage-specific inputs
                - configs: Project configuration
                - previous_results: Outputs from previous stages

        Returns:
            AgentResult with success status, artifacts, and metrics

        Raises:
            AgentError: For expected errors (converted to AgentResult by wrapper)
        """
        pass

    def validate_inputs(self, context: dict[str, Any]) -> tuple[bool, list[str]]:
        """Validate that all required input files exist.

        Args:
            context: Execution context containing project_dir

        Returns:
            Tuple of (all_exist, list_of_missing_files)
        """
        project_dir = Path(context.get("project_dir", "."))
        missing: list[str] = []

        for input_file in self.required_inputs:
            full_path = project_dir / input_file
            if not full_path.exists():
                missing.append(str(input_file))

        return len(missing) == 0, missing

    def validate_outputs(
        self, context: dict[str, Any]
    ) -> tuple[bool, list[str], list[str]]:
        """Validate that expected output artifacts were created.

        Args:
            context: Execution context containing project_dir

        Returns:
            Tuple of (all_exist, list_of_found_files, list_of_missing_patterns)
        """
        project_dir = Path(context.get("project_dir", "."))
        workspace_dir = project_dir / "workspace"
        found: list[str] = []
        missing: list[str] = []

        for pattern in self.output_artifacts:
            # Handle both direct paths and glob patterns
            if "*" in pattern or "?" in pattern:
                matches = list(workspace_dir.glob(pattern.replace("workspace/", "")))
                if matches:
                    found.extend(str(m) for m in matches)
                else:
                    missing.append(pattern)
            else:
                full_path = project_dir / pattern
                if full_path.exists():
                    found.append(str(full_path))
                else:
                    missing.append(pattern)

        return len(missing) == 0, found, missing

    def render_prompt(self, context: dict[str, Any]) -> str:
        """Read the prompt file and substitute {{KEY}} placeholders.

        Args:
            context: Dictionary of template variables. Keys like
                     "PROJECT_DIR", "MODULE_NAME", etc. will replace
                     corresponding {{PROJECT_DIR}}, {{MODULE_NAME}} tokens.

        Returns:
            Rendered prompt string with all matching placeholders replaced.

        Raises:
            LLMInvocationError: If the prompt file is not found or empty.
        """
        if not self.prompt_file:
            raise LLMInvocationError("No prompt file configured for this agent")

        prompt_path = Path("prompts") / self.prompt_file
        if not prompt_path.exists() or not prompt_path.is_file():
            raise LLMInvocationError(f"Prompt file not found: {prompt_path}")

        content = prompt_path.read_text(encoding="utf-8")

        for key, value in context.items():
            placeholder = "{{" + key + "}}"
            content = content.replace(placeholder, str(value))

        return content

    def call_llm(
        self,
        context: dict[str, Any],
        prompt_override: str | None = None,
        system_prompt: str | None = None,
    ) -> str:
        """Invoke the LLM with the configured backend.

        Supports multiple backends:
        - "claude_cli": Use Claude CLI subprocess (legacy, backward compatible)
        - "anthropic": Use Anthropic Python SDK
        - "langchain": Use LangChain abstraction

        Args:
            context: Execution context with prompt variables
            prompt_override: Optional override for the prompt file content
            system_prompt: Optional system prompt to prepend

        Returns:
            Raw LLM output as string

        Raises:
            LLMInvocationError: If the LLM call fails
        """
        if self.llm_backend == "claude_cli":
            return self._call_llm_claude_cli(context, prompt_override, system_prompt)
        elif self.llm_backend == "anthropic":
            return self._call_llm_anthropic(context, prompt_override, system_prompt)
        elif self.llm_backend == "langchain":
            return self._call_llm_langchain(context, prompt_override, system_prompt)
        else:
            raise LLMInvocationError(f"Unknown LLM backend: {self.llm_backend}")

    def _call_llm_claude_cli(
        self,
        context: dict[str, Any],
        prompt_override: str | None = None,
        system_prompt: str | None = None,
    ) -> str:
        """Call LLM using Claude CLI subprocess (backward compatible)."""
        import json
        import subprocess

        # Find claude CLI
        claude_exe = self._find_claude_cli()
        if not claude_exe:
            raise LLMInvocationError("Claude CLI not found. Please install Claude CLI.")

        # Read prompt file or use override
        if prompt_override:
            prompt_content = prompt_override
        else:
            prompt_path = Path("prompts") / self.prompt_file
            if not prompt_path.exists():
                raise LLMInvocationError(f"Prompt file not found: {prompt_path}")
            prompt_content = prompt_path.read_text(encoding="utf-8")

        # Prepend system prompt if provided
        if system_prompt:
            prompt_content = f"{system_prompt}\n\n{prompt_content}"

        # Prepare stdin data
        stdin_data = {
            "prompt": prompt_content,
            "context": context,
        }

        # Call Claude CLI
        try:
            result = subprocess.run(
                [claude_exe, "--print", "--dangerously-skip-permissions"],
                input=json.dumps(stdin_data),
                capture_output=True,
                text=True,
                timeout=600,  # 10 minute timeout
            )

            if result.returncode != 0:
                raise LLMInvocationError(
                    f"Claude CLI failed with code {result.returncode}: {result.stderr}"
                )

            return result.stdout

        except subprocess.TimeoutExpired:
            raise LLMInvocationError("Claude CLI timed out after 10 minutes")
        except Exception as e:
            raise LLMInvocationError(f"Failed to invoke Claude CLI: {e}")

    def _call_llm_anthropic(
        self,
        context: dict[str, Any],
        prompt_override: str | None = None,
        system_prompt: str | None = None,
    ) -> str:
        """Call LLM using Anthropic Python SDK."""
        try:
            import anthropic
        except ImportError:
            raise LLMInvocationError(
                "anthropic package not installed. Run: pip install anthropic"
            )

        # Initialize client
        api_key = os.environ.get("ANTHROPIC_API_KEY")
        if not api_key:
            raise LLMInvocationError("ANTHROPIC_API_KEY environment variable not set")

        client = anthropic.Anthropic(api_key=api_key)

        # Read prompt
        if prompt_override:
            prompt_content = prompt_override
        else:
            prompt_path = Path("prompts") / self.prompt_file
            if not prompt_path.exists():
                raise LLMInvocationError(f"Prompt file not found: {prompt_path}")
            prompt_content = prompt_path.read_text(encoding="utf-8")

        # Call API
        try:
            message = client.messages.create(
                model="claude-3-sonnet-20240229",  # Configurable
                max_tokens=4096,
                temperature=0.1,
                system=system_prompt if system_prompt else None,
                messages=[{"role": "user", "content": prompt_content}],
            )
            return message.content[0].text
        except Exception as e:
            raise LLMInvocationError(f"Anthropic API call failed: {e}")

    def _call_llm_langchain(
        self,
        context: dict[str, Any],
        prompt_override: str | None = None,
        system_prompt: str | None = None,
    ) -> str:
        """Call LLM using LangChain abstraction."""
        try:
            from langchain_core.prompts import ChatPromptTemplate
            from langchain_anthropic import ChatAnthropic
        except ImportError:
            raise LLMInvocationError(
                "langchain packages not installed. Run: pip install langchain-core langchain-anthropic"
            )

        # Initialize model
        model = ChatAnthropic(
            model="claude-3-sonnet-20240229",
            temperature=0.1,
            max_tokens=4096,
        )

        # Read prompt
        if prompt_override:
            prompt_content = prompt_override
        else:
            prompt_path = Path("prompts") / self.prompt_file
            if not prompt_path.exists():
                raise LLMInvocationError(f"Prompt file not found: {prompt_path}")
            prompt_content = prompt_path.read_text(encoding="utf-8")

        # Create prompt template
        messages = [("human", prompt_content)]
        if system_prompt:
            messages.insert(0, ("system", system_prompt))

        prompt = ChatPromptTemplate.from_messages(messages)

        # Create chain and invoke
        chain = prompt | model
        try:
            result = chain.invoke(context)
            return result.content
        except Exception as e:
            raise LLMInvocationError(f"LangChain invocation failed: {e}")

    def _find_claude_cli(self) -> str | None:
        """Find the Claude CLI executable.

        Searches in common locations and PATH.

        Returns:
            Path to claude executable or None if not found
        """
        import shutil

        # Check PATH first
        for name in ["claude", "claude.cmd", "claude.bat", "claude.exe"]:
            found = shutil.which(name)
            if found:
                return found

        # Check common install locations
        home = Path.home()
        candidates = [
            home / ".claude" / "local" / "claude",
            home / ".claude" / "local" / "claude.exe",
            home / "AppData" / "Roaming" / "npm" / "claude.cmd",
            home / "AppData" / "Roaming" / "npm" / "claude",
            home / "AppData" / "Local" / "Programs" / "claude" / "claude.exe",
            Path("/usr/local/bin/claude"),
            Path("/opt/homebrew/bin/claude"),
        ]

        for p in candidates:
            if p.exists():
                return str(p)

        return None