"""Base Agent class for VeriFlow-Agent.

This module defines the abstract base class that all pipeline stage agents
must inherit from. It provides common functionality for:
- LLM invocation (supporting multiple backends)
- Input/output validation
- Error handling and retry logic
- Metrics collection
- Real-time observability via streaming events
"""

from __future__ import annotations

import logging
import os
import re
import subprocess
from abc import ABC, abstractmethod
from collections.abc import Generator
from dataclasses import dataclass, field
from pathlib import Path
from typing import TYPE_CHECKING, Any

if TYPE_CHECKING:
    pass

# Observability imports for streaming support
from veriflow_agent.observability import (
    EventCollector,
    LLMEvent,
    create_error_event,
    create_metrics_event,
    create_session_init_event,
    create_stream_end_event,
    create_text_delta_event,
    create_tool_complete_event,
    create_tool_error_event,
    create_tool_start_event,
)

logger = logging.getLogger("veriflow.agent")

# Security: --dangerously-skip-permissions is opt-in for automated pipelines.
# Set VERIFLOW_SKIP_PERMISSIONS=true to enable (required for headless CI/CD).
_SKIP_PERMS = os.environ.get("VERIFLOW_SKIP_PERMISSIONS", "false").lower() in ("true", "1", "yes")


@dataclass
class AgentResult:
    """Standardized result format for all agent executions.

    This dataclass ensures consistent output structure across all pipeline stages,
    making it easy to handle results uniformly in the graph state machine.

    Attributes:
        success: Whether the stage completed successfully
        stage: Name of the stage (e.g., "architect", "coder")
        artifacts: List of file paths generated by this stage
        metrics: Key performance indicators (e.g., token count, time taken)
        errors: List of error messages if stage failed
        warnings: List of non-fatal warning messages
        raw_output: Raw LLM output for debugging
        metadata: Additional stage-specific data
    """

    success: bool
    stage: str
    artifacts: list[str] = field(default_factory=list)
    metrics: dict[str, Any] = field(default_factory=dict)
    errors: list[str] = field(default_factory=list)
    warnings: list[str] = field(default_factory=list)
    raw_output: str = ""
    metadata: dict[str, Any] = field(default_factory=dict)

    def to_dict(self) -> dict[str, Any]:
        """Convert to dictionary for serialization (e.g., JSON checkpoint)."""
        return {
            "success": self.success,
            "stage": self.stage,
            "artifacts": self.artifacts,
            "metrics": self.metrics,
            "errors": self.errors,
            "warnings": self.warnings,
            "raw_output": self.raw_output,
            "metadata": self.metadata,
        }

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> AgentResult:
        """Create from dictionary (e.g., when loading checkpoint)."""
        return cls(
            success=data.get("success", False),
            stage=data.get("stage", ""),
            artifacts=data.get("artifacts", []),
            metrics=data.get("metrics", {}),
            errors=data.get("errors", []),
            warnings=data.get("warnings", []),
            raw_output=data.get("raw_output", ""),
            metadata=data.get("metadata", {}),
        )


class AgentError(Exception):
    """Base exception for agent-related errors."""

    def __init__(self, message: str, stage: str = "", details: dict | None = None):
        super().__init__(message)
        self.stage = stage
        self.details = details or {}


class InputValidationError(AgentError):
    """Raised when input validation fails."""

    pass


class OutputValidationError(AgentError):
    """Raised when output validation fails."""

    pass


class LLMInvocationError(AgentError):
    """Raised when LLM invocation fails."""

    pass


class BaseAgent(ABC):
    """Abstract base class for all VeriFlow pipeline stage agents.

    This class provides the common infrastructure that all agents need:
    - LLM invocation with multiple backend support
    - Input/output file validation
    - Structured error handling
    - Metrics collection

    Subclasses must implement the `execute` method to define their specific logic.

    Example:
        ```python
        class MyAgent(BaseAgent):
            def __init__(self):
                super().__init__(
                    name="my_agent",
                    prompt_file="stage_my.md",
                    required_inputs=["workspace/docs/spec.json"],
                    output_artifacts=["workspace/rtl/output.v"]
                )

            def execute(self, context):
                # Implementation here
                pass
        ```
    """

    def __init__(
        self,
        name: str,
        prompt_file: str,
        required_inputs: list[str] | None = None,
        output_artifacts: list[str] | None = None,
        max_retries: int = 3,
        llm_backend: str = "openai",  # "openai" | "langchain"
    ):
        """Initialize the agent.

        Args:
            name: Unique identifier for this agent (e.g., "architect", "coder")
            prompt_file: Name of the prompt file in prompts/ directory
            required_inputs: List of input file paths (relative to project_dir)
            output_artifacts: List of expected output file patterns
            max_retries: Maximum number of retry attempts on failure
            llm_backend: Which LLM invocation method to use
        """
        self.name = name
        self.prompt_file = prompt_file
        self.required_inputs = required_inputs or []
        self.output_artifacts = output_artifacts or []
        self.max_retries = max_retries
        self.llm_backend = llm_backend

        # Configurable LLM client (initialized on first use)
        self._llm_client: Any | None = None

    @abstractmethod
    def execute(self, context: dict[str, Any]) -> AgentResult:
        """Execute the agent's main logic.

        This is the main entry point that subclasses must implement.
        It should:
        1. Validate inputs using `validate_inputs()`
        2. Perform the stage's core logic
        3. Validate outputs using `validate_outputs()`
        4. Return a properly structured AgentResult

        Args:
            context: Dictionary containing:
                - project_dir: Path to project root
                - inputs: Stage-specific inputs
                - configs: Project configuration
                - previous_results: Outputs from previous stages

        Returns:
            AgentResult with success status, artifacts, and metrics

        Raises:
            AgentError: For expected errors (converted to AgentResult by wrapper)
        """
        pass

    def validate_inputs(self, context: dict[str, Any]) -> tuple[bool, list[str]]:
        """Validate that all required input files exist.

        Args:
            context: Execution context containing project_dir

        Returns:
            Tuple of (all_exist, list_of_missing_files)
        """
        project_dir = Path(context.get("project_dir", "."))
        missing: list[str] = []

        for input_file in self.required_inputs:
            full_path = project_dir / input_file
            if not full_path.exists():
                missing.append(str(input_file))

        if missing:
            logger.warning("[%s] Input validation: missing %s", self.name, missing)
        else:
            logger.debug("[%s] Input validation: all inputs present", self.name)

        return len(missing) == 0, missing

    def validate_outputs(
        self, context: dict[str, Any]
    ) -> tuple[bool, list[str], list[str]]:
        """Validate that expected output artifacts were created.

        Args:
            context: Execution context containing project_dir

        Returns:
            Tuple of (all_exist, list_of_found_files, list_of_missing_patterns)
        """
        project_dir = Path(context.get("project_dir", "."))
        workspace_dir = project_dir / "workspace"
        found: list[str] = []
        missing: list[str] = []

        for pattern in self.output_artifacts:
            # Handle both direct paths and glob patterns
            if "*" in pattern or "?" in pattern:
                matches = list(workspace_dir.glob(pattern.replace("workspace/", "")))
                if matches:
                    found.extend(str(m) for m in matches)
                else:
                    missing.append(pattern)
            else:
                full_path = project_dir / pattern
                if full_path.exists():
                    found.append(str(full_path))
                else:
                    missing.append(pattern)

        if missing:
            logger.warning("[%s] Output validation: missing %s", self.name, missing)
        elif self.output_artifacts:
            logger.debug("[%s] Output validation: all %d artifacts found", self.name, len(found))

        return len(missing) == 0, found, missing

    def _resolve_prompt_path(self) -> Path:
        """Resolve prompt file path with CWD and package fallback."""
        # Attempt 1: CWD-relative (useful during development)
        prompt_path = Path("prompts") / self.prompt_file
        if prompt_path.exists() and prompt_path.is_file():
            return prompt_path
        # Attempt 2: Package-relative (works in pip-installed packages)
        # __file__ = .../veriflow_agent/agents/base.py → parent.parent = .../veriflow_agent/
        pkg_prompt = Path(__file__).resolve().parent.parent / "prompts" / self.prompt_file
        if pkg_prompt.exists() and pkg_prompt.is_file():
            return pkg_prompt
        raise LLMInvocationError(
            f"Prompt file not found: {self.prompt_file} "
            f"(tried CWD 'prompts/' and package-relative)"
        )

    def render_prompt(self, context: dict[str, Any]) -> str:
        """Read the prompt file and substitute {{KEY}} placeholders.

        Args:
            context: Dictionary of template variables. Keys like
                     "PROJECT_DIR", "MODULE_NAME", etc. will replace
                     corresponding {{PROJECT_DIR}}, {{MODULE_NAME}} tokens.

        Returns:
            Rendered prompt string with all matching placeholders replaced.

        Raises:
            LLMInvocationError: If the prompt file is not found or empty.
        """
        if not self.prompt_file:
            raise LLMInvocationError("No prompt file configured for this agent")

        prompt_path = self._resolve_prompt_path()
        content = prompt_path.read_text(encoding="utf-8")

        for key, value in context.items():
            placeholder = "{{" + key + "}}"
            content = content.replace(placeholder, str(value))

        logger.debug("[%s] Rendered prompt from %s (%d chars)", self.name, prompt_path.name, len(content))
        return content

    def call_llm(
        self,
        context: dict[str, Any],
        prompt_override: str | None = None,
        system_prompt: str | None = None,
    ) -> str:
        """Invoke the LLM using stream consumption for real-time UI observability.
        
        This wraps call_llm_streaming to guarantee that all agents automatically
        emit TEXT_DELTA chunks to veriflow.stream, driving the Live Terminal UI,
        even if the agent itself didn't explicitly request streaming.
        
        Args:
            context: Execution context with prompt variables
            prompt_override: Optional override for the prompt file content
            system_prompt: Optional system prompt to prepend

        Returns:
            Raw LLM output as string

        Raises:
            LLMInvocationError: If the LLM call fails
        """
        self._last_token_usage = 0
        prompt = prompt_override or self._resolve_prompt_path().read_text(encoding="utf-8")
        event_collector = context.get("_event_collector")
        
        # Transparently proxy to consume streaming to hijack text events
        return self._consume_streaming(
            context,
            prompt,
            event_collector=event_collector,
            system_prompt=system_prompt,
        )

    def get_last_token_usage(self) -> int:
        """Get the estimated token usage from the most recent LLM call.

        Returns:
            Estimated token count (0 if no call made yet).
        """
        return getattr(self, "_last_token_usage", 0)

    @staticmethod
    def sanitize_module_name(name: str) -> str:
        """Sanitize LLM-extracted module name for filesystem safety.

        Removes any character that is not alphanumeric or underscore.
        Prevents path traversal attacks from malicious LLM output.

        Args:
            name: Raw module name extracted from LLM output.

        Returns:
            Safe module name string, or "unnamed" if result is empty.
        """
        safe = re.sub(r'[^a-zA-Z0-9_]', '', name)
        return safe if safe else "unnamed"

    def _estimate_tokens(self, text: str) -> int:
        """Rough token estimate: ~4 chars per token for English/code.

        Args:
            text: Text to estimate token count for.

        Returns:
            Estimated token count.
        """
        return max(1, len(text) // 4)

    def _consume_streaming(
        self,
        context: dict[str, Any],
        prompt: str,
        event_collector: EventCollector | None = None,
        system_prompt: str | None = None,
    ) -> str:
        """Consume streaming LLM call and return accumulated text.

        Handles the mixed LLMEvent/AgentResult yield types from
        call_llm_streaming, providing a clean string return for callers.

        Args:
            context: Execution context.
            prompt: Rendered prompt string.
            event_collector: Optional event collector for observability.

        Returns:
            Accumulated LLM output text.

        Raises:
            LLMInvocationError: If the streaming call reports failure.
        """
        import json as _json
        stream_logger = logging.getLogger("veriflow.stream")

        for item in self.call_llm_streaming(
            context,
            prompt_override=prompt,
            system_prompt=system_prompt,
            event_collector=event_collector,
        ):
            if isinstance(item, AgentResult):
                if not item.success:
                    raise LLMInvocationError(
                        f"LLM streaming failed: {item.errors}"
                    )
                return item.raw_output

            elif hasattr(item, "event_type"):
                etype = (
                    item.event_type.name
                    if hasattr(item.event_type, "name")
                    else str(item.event_type)
                )

                if etype == "TEXT_DELTA":
                    chunk = item.payload.get("text", "")
                    if chunk:
                        # Prefix "TEXT:" so WSLogHandler can parse the event type
                        stream_logger.info("TEXT:" + chunk)

                elif etype == "TOOL_START":
                    data = _json.dumps({
                        "tool_name": item.payload.get("tool_name", "unknown"),
                        "call_id": item.payload.get("call_id", ""),
                        "stage": self.name,
                    })
                    stream_logger.info("TOOL_START:" + data)

                elif etype in ("TOOL_COMPLETE", "TOOL_ERROR"):
                    success = etype == "TOOL_COMPLETE"
                    data = _json.dumps({
                        "call_id": item.payload.get("call_id", ""),
                        "success": success,
                        "error": item.payload.get("error", "") if not success else "",
                        "stage": self.name,
                    })
                    stream_logger.info("TOOL_END:" + data)

        raise LLMInvocationError("LLM streaming ended without returning a result")

    def _call_llm_claude_cli(
        self,
        context: dict[str, Any],
        prompt_override: str | None = None,
        system_prompt: str | None = None,
    ) -> str:
        """Call LLM using Claude CLI subprocess (backward compatible)."""
        # Find claude CLI
        claude_exe = self._find_claude_cli()
        if not claude_exe:
            raise LLMInvocationError("Claude CLI not found. Please install Claude CLI.")

        # Read prompt file or use override
        if prompt_override:
            prompt_content = prompt_override
        else:
            prompt_path = self._resolve_prompt_path()
            prompt_content = prompt_path.read_text(encoding="utf-8")

        # Prepend system prompt if provided
        if system_prompt:
            prompt_content = f"{system_prompt}\n\n{prompt_content}"

        # Call Claude CLI
        try:
            cmd = [claude_exe, "--print"]
            if _SKIP_PERMS:
                cmd.append("--dangerously-skip-permissions")
            result = subprocess.run(
                cmd,
                input=prompt_content.encode("utf-8"),
                capture_output=True,
                timeout=1800,  # 30 minute timeout for complex designs
            )
            stdout = result.stdout.decode("utf-8", errors="replace")
            stderr = result.stderr.decode("utf-8", errors="replace")

            if result.returncode != 0:
                raise LLMInvocationError(
                    f"Claude CLI failed with code {result.returncode}: {stderr}"
                )

            # Estimate token usage
            self._last_token_usage = self._estimate_tokens(prompt_content) + self._estimate_tokens(stdout)

            return stdout

        except subprocess.TimeoutExpired:
            raise LLMInvocationError("Claude CLI timed out after 30 minutes")
        except Exception as e:
            raise LLMInvocationError(f"Failed to invoke Claude CLI: {e}")

    def _call_llm_langchain(
        self,
        context: dict[str, Any],
        prompt_override: str | None = None,
        system_prompt: str | None = None,
    ) -> str:
        """Call LLM using LangChain abstraction."""
        try:
            from langchain_anthropic import ChatAnthropic
            from langchain_core.prompts import ChatPromptTemplate
        except ImportError:
            raise LLMInvocationError(
                "langchain packages not installed. Run: pip install langchain-core langchain-anthropic"
            )

        # Initialize model
        model = ChatAnthropic(
            model=os.environ.get("VERIFLOW_MODEL", "claude-sonnet-4-6"),
            temperature=0.1,
            max_tokens=4096,
        )

        # Read prompt
        if prompt_override:
            prompt_content = prompt_override
        else:
            prompt_content = self._resolve_prompt_path().read_text(encoding="utf-8")

        # Create prompt template
        messages = [("human", prompt_content)]
        if system_prompt:
            messages.insert(0, ("system", system_prompt))

        prompt = ChatPromptTemplate.from_messages(messages)

        # Create chain and invoke
        chain = prompt | model
        try:
            result = chain.invoke(context)
            # Track token usage from LangChain response metadata
            token_count = 0
            if hasattr(result, "response_metadata"):
                usage = result.response_metadata.get("usage", {})
                token_count = usage.get("input_tokens", 0) + usage.get("output_tokens", 0)
            if token_count == 0:
                token_count = self._estimate_tokens(prompt_content) + self._estimate_tokens(result.content)
            self._last_token_usage = token_count
            return result.content
        except Exception as e:
            raise LLMInvocationError(f"LangChain invocation failed: {e}")

    def _find_claude_cli(self) -> str | None:
        """Find the Claude CLI executable.

        Searches in common locations and PATH.

        Returns:
            Path to claude executable or None if not found
        """
        import shutil

        # Check PATH first
        for name in ["claude", "claude.cmd", "claude.bat", "claude.exe"]:
            found = shutil.which(name)
            if found:
                return found

        # Check common install locations
        home = Path.home()
        candidates = [
            home / ".claude" / "local" / "claude",
            home / ".claude" / "local" / "claude.exe",
            home / "AppData" / "Roaming" / "npm" / "claude.cmd",
            home / "AppData" / "Roaming" / "npm" / "claude",
            home / "AppData" / "Local" / "Programs" / "claude" / "claude.exe",
            Path("/usr/local/bin/claude"),
            Path("/opt/homebrew/bin/claude"),
        ]

        for p in candidates:
            if p.exists():
                return str(p)

        return None

    # === NEW: Streaming LLM Methods for Real-time Observability ===

    def call_llm_streaming(
        self,
        context: dict[str, Any],
        prompt_override: str | None = None,
        system_prompt: str | None = None,
        event_collector: EventCollector | None = None,
    ) -> Generator[LLMEvent | AgentResult, None, None]:
        """Invoke the LLM with streaming and event collection.

        This method provides real-time observability by yielding events
        during LLM execution. Events include text deltas, tool calls,
        metrics updates, and completion status.

        Args:
            context: Execution context with prompt variables
            prompt_override: Optional override for the prompt file content
            system_prompt: Optional system prompt to prepend
            event_collector: Optional collector to receive all events

        Yields:
            LLMEvent: Real-time events during execution (text_delta, tool_start, etc.)

        Returns:
            AgentResult: Final result with success status, artifacts, metrics

        Example:
            ```python
            collector = EventCollector("coder")
            for event in agent.call_llm_streaming(context, event_collector=collector):
                if event.event_type == EventType.TEXT_DELTA:
                    print(event.payload["text"], end="")

            result = collector.get_result()
            trace = collector.get_trace()
            ```
        """
        self._last_token_usage = 0
        logger.info("[%s] Calling LLM via %s backend (streaming)", self.name, self.llm_backend)

        if self.llm_backend == "claude_cli":
            raise LLMInvocationError(
                "claude_cli backend is disabled. Set llm_backend='openai' or 'langchain'."
            )
        elif self.llm_backend in ("openai", "anthropic"):
            # Both route to the OpenAI-compatible implementation.
            # Anthropic is kept as an alias so existing configs don't break.
            yield from self._call_llm_openai_streaming(
                context, prompt_override, system_prompt, event_collector
            )
        elif self.llm_backend == "langchain":
            yield from self._call_llm_langchain_streaming(
                context, prompt_override, system_prompt, event_collector
            )
        else:
            raise LLMInvocationError(f"Unknown LLM backend: {self.llm_backend}")

    def _call_llm_claude_cli_streaming(
        self,
        context: dict[str, Any],  # noqa: ARG002 — kept for interface symmetry; callers pass rendered prompt via prompt_override
        prompt_override: str | None,
        system_prompt: str | None,
        event_collector: EventCollector | None,
    ) -> Generator[LLMEvent | AgentResult, None, None]:
        """Call LLM using Claude CLI with stream-json output format.

        This implementation uses --output-format stream-json to receive
        real-time events from the Claude CLI subprocess.
        """
        import json as json_mod
        import subprocess

        claude_exe = self._find_claude_cli()
        if not claude_exe:
            raise LLMInvocationError("Claude CLI not found. Please install Claude Code.")

        # Build prompt
        if prompt_override:
            prompt_content = prompt_override
        else:
            prompt_path = self._resolve_prompt_path()
            prompt_content = prompt_path.read_text(encoding="utf-8")

        if system_prompt:
            prompt_content = f"{system_prompt}\n\n{prompt_content}"

        # Build command with stream-json
        cmd = [
            claude_exe,
            "--print",
            "--verbose",
            "--output-format", "stream-json",
        ]
        if _SKIP_PERMS:
            cmd.append("--dangerously-skip-permissions")

        # Start subprocess
        try:
            proc = subprocess.Popen(
                cmd,
                stdin=subprocess.PIPE,
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE,
                text=True,
                encoding="utf-8",
                errors="replace",
            )
        except Exception as e:
            raise LLMInvocationError(f"Failed to start Claude CLI: {e}")

        # Send prompt
        try:
            proc.stdin.write(prompt_content)
            proc.stdin.close()
        except Exception as e:
            raise LLMInvocationError(f"Failed to send prompt to Claude CLI: {e}")

        # Process stream
        text_parts = []
        api_success = False
        session_info = {}

        try:
            for line in proc.stdout:
                line = line.rstrip()
                if not line:
                    continue

                try:
                    event_data = json_mod.loads(line)
                except json_mod.JSONDecodeError:
                    continue

                # Parse event and yield
                event_type = event_data.get("type", "")

                if event_type == "system" and event_data.get("subtype") == "init":
                    session_info = {
                        "session_id": event_data.get("session_id", ""),
                        "tools": event_data.get("tools", []),
                    }
                    event = create_session_init_event(
                        stage=self.name,
                        session_id=session_info.get("session_id", ""),
                        tools=session_info.get("tools", []),
                    )
                    if event_collector:
                        event_collector.on_event(event)
                    yield event

                elif event_type == "assistant":
                    msg = event_data.get("message", {})
                    for block in msg.get("content", []):
                        if not isinstance(block, dict):
                            continue

                        btype = block.get("type", "")

                        if btype == "text":
                            text = block.get("text", "")
                            text_parts.append(text)
                            event = create_text_delta_event(
                                stage=self.name,
                                text=text,
                                cumulative_text="".join(text_parts),
                                token_index=len(text_parts),
                            )
                            if event_collector:
                                event_collector.on_event(event)
                            yield event

                        elif btype == "tool_use":
                            event = create_tool_start_event(
                                stage=self.name,
                                tool_name=block.get("name", ""),
                                tool_input=block.get("input", {}),
                                call_id=block.get("id", ""),
                            )
                            if event_collector:
                                event_collector.on_event(event)
                            yield event

                    # Check usage
                    usage = msg.get("usage", {})
                    if usage:
                        event = create_metrics_event(
                            stage=self.name,
                            input_tokens=usage.get("input_tokens", 0),
                            output_tokens=usage.get("output_tokens", 0),
                        )
                        if event_collector:
                            event_collector.on_event(event)
                        yield event

                elif event_type == "user":
                    # Tool result
                    for block in event_data.get("message", {}).get("content", []):
                        if block.get("type") == "tool_result":
                            is_error = block.get("is_error", False)
                            if is_error:
                                event = create_tool_error_event(
                                    stage=self.name,
                                    call_id=block.get("tool_use_id", ""),
                                    error=block.get("content", "Tool failed"),
                                )
                            else:
                                event = create_tool_complete_event(
                                    stage=self.name,
                                    call_id=block.get("tool_use_id", ""),
                                    tool_output={"content": block.get("content", "")},
                                )
                            if event_collector:
                                event_collector.on_event(event)
                            yield event

                elif event_type == "result":
                    api_success = event_data.get("subtype") == "success"
                    event = create_stream_end_event(
                        stage=self.name,
                        success=api_success,
                        error_message="" if api_success else "Claude CLI returned error",
                        duration_ms=event_data.get("duration_ms", 0),
                    )
                    if event_collector:
                        event_collector.on_event(event)
                    yield event

        finally:
            # Wait for process to complete; escalate to kill() on Unix if
            # terminate() (SIGTERM) is ignored, to prevent indefinite hang.
            try:
                proc.wait(timeout=30)
            except subprocess.TimeoutExpired:
                proc.terminate()
                try:
                    proc.wait(timeout=5)
                except subprocess.TimeoutExpired:
                    proc.kill()
                    proc.wait()

        # Build final result
        output = "".join(text_parts)
        success = api_success or "STAGE_COMPLETE" in output

        # Estimate token usage
        self._last_token_usage = (
            self._estimate_tokens(prompt_content) + self._estimate_tokens(output)
        )

        # Capture stderr for error diagnostics when the CLI reports failure
        stderr_output = ""
        try:
            stderr_output = proc.stderr.read() if proc.stderr else ""
        except Exception:
            pass

        result = AgentResult(
            success=success,
            stage=self.name,
            raw_output=output,
            metrics={"token_usage": self._last_token_usage},
            errors=(
                [f"Claude CLI exited with failure. stderr: {stderr_output[:500]}"]
                if not success else []
            ),
        )

        yield result

    def _call_llm_openai_streaming(
        self,
        context: dict[str, Any],
        prompt_override: str | None,
        system_prompt: str | None,
        event_collector: EventCollector | None,
    ) -> Generator[LLMEvent | AgentResult, None, None]:
        """Call LLM using OpenAI-compatible API with streaming.

        Works with any OpenAI-compatible endpoint (OpenAI, Anthropic via
        openai-compat, local vLLM, LM Studio, etc.).

        Config priority: context dict (from VeriFlowState) → env vars → default.
        """
        try:
            from openai import OpenAI
        except ImportError:
            raise LLMInvocationError(
                "openai package not installed. Run: pip install openai"
            )

        api_key = (
            context.get("llm_api_key", "")
            or os.environ.get("OPENAI_API_KEY", "")
        )
        if not api_key:
            raise LLMInvocationError(
                "API key not configured. Set it in the Settings panel or via OPENAI_API_KEY."
            )

        base_url = context.get("llm_base_url", "") or os.environ.get("OPENAI_BASE_URL") or None
        model = (
            context.get("llm_model", "")
            or os.environ.get("VERIFLOW_MODEL", "")
            or os.environ.get("OPENAI_MODEL", "gpt-4o")
        )

        client = OpenAI(api_key=api_key, base_url=base_url)

        # Build prompt
        if prompt_override:
            prompt_content = prompt_override
        else:
            prompt_path = self._resolve_prompt_path()
            prompt_content = prompt_path.read_text(encoding="utf-8")

        messages: list[dict[str, str]] = []
        if system_prompt:
            messages.append({"role": "system", "content": system_prompt})
        messages.append({"role": "user", "content": prompt_content})

        try:
            text_parts: list[str] = []
            input_tokens = 0
            output_tokens = 0

            # Session init event
            event = create_session_init_event(
                stage=self.name,
                session_id="openai_sdk",
                tools=[],
            )
            if event_collector:
                event_collector.on_event(event)
            yield event

            stream = client.chat.completions.create(
                model=model,
                messages=messages,
                max_tokens=8192,
                temperature=0.1,
                stream=True,
                stream_options={"include_usage": True},
            )

            for chunk in stream:
                # Usage is provided in the final chunk when stream_options include_usage=True
                if chunk.usage:
                    input_tokens = chunk.usage.prompt_tokens or 0
                    output_tokens = chunk.usage.completion_tokens or 0

                if not chunk.choices:
                    continue
                delta = chunk.choices[0].delta
                text = delta.content or ""
                if not text:
                    continue

                text_parts.append(text)
                event = create_text_delta_event(
                    stage=self.name,
                    text=text,
                    cumulative_text="".join(text_parts),
                    token_index=len(text_parts),
                )
                if event_collector:
                    event_collector.on_event(event)
                yield event

            # Fallback token estimate if API didn't return usage
            if input_tokens == 0 and output_tokens == 0:
                input_tokens = self._estimate_tokens(prompt_content)
                output_tokens = self._estimate_tokens("".join(text_parts))

            event = create_metrics_event(
                stage=self.name,
                input_tokens=input_tokens,
                output_tokens=output_tokens,
            )
            if event_collector:
                event_collector.on_event(event)
            yield event

            event = create_stream_end_event(stage=self.name, success=True, duration_ms=0)
            if event_collector:
                event_collector.on_event(event)
            yield event

            output = "".join(text_parts)
            self._last_token_usage = input_tokens + output_tokens

            yield AgentResult(
                success=True,
                stage=self.name,
                raw_output=output,
                metrics={
                    "token_usage": self._last_token_usage,
                    "input_tokens": input_tokens,
                    "output_tokens": output_tokens,
                },
            )

        except Exception as e:
            event = create_error_event(stage=self.name, error=str(e))
            if event_collector:
                event_collector.on_event(event)
            yield event

            event = create_stream_end_event(stage=self.name, success=False, error_message=str(e))
            if event_collector:
                event_collector.on_event(event)
            yield event

            raise LLMInvocationError(f"OpenAI-compatible API streaming failed: {e}")

    def _call_llm_langchain_streaming(
        self,
        context: dict[str, Any],  # noqa: ARG002 — kept for interface symmetry; callers pass rendered prompt via prompt_override
        prompt_override: str | None,
        system_prompt: str | None,
        event_collector: EventCollector | None,
    ) -> Generator[LLMEvent | AgentResult, None, None]:
        """Call LLM using LangChain with streaming.

        This implementation uses LangChain's callback system to receive
        real-time events during LLM execution.
        """
        try:
            from langchain_anthropic import ChatAnthropic
            from langchain_core.callbacks import BaseCallbackHandler
            from langchain_core.prompts import ChatPromptTemplate
        except ImportError:
            raise LLMInvocationError(
                "langchain packages not installed. Run: pip install langchain-core langchain-anthropic"
            )

        # Read prompt
        if prompt_override:
            prompt_content = prompt_override
        else:
            prompt_path = self._resolve_prompt_path()
            prompt_content = prompt_path.read_text(encoding="utf-8")

        # Create custom callback handler for events
        class ObservabilityCallback(BaseCallbackHandler):
            def __init__(self, stage: str, collector: EventCollector | None):
                self.stage = stage
                self.collector = collector
                self.text_parts = []
                self.tool_calls = 0

            def on_llm_start(self, serialized, prompts, **kwargs):
                event = create_session_init_event(
                    stage=self.stage,
                    session_id="langchain",
                    tools=[],
                )
                if self.collector:
                    self.collector.on_event(event)

            def on_llm_new_token(self, token: str, **kwargs):
                self.text_parts.append(token)
                event = create_text_delta_event(
                    stage=self.stage,
                    text=token,
                    cumulative_text="".join(self.text_parts),
                    token_index=len(self.text_parts),
                )
                if self.collector:
                    self.collector.on_event(event)

            def on_tool_start(self, serialized, input_str, **kwargs):
                self.tool_calls += 1
                event = create_tool_start_event(
                    stage=self.stage,
                    tool_name=serialized.get("name", "unknown"),
                    tool_input={"input": input_str},
                    call_id=str(self.tool_calls),
                )
                if self.collector:
                    self.collector.on_event(event)

            def on_tool_end(self, output, **kwargs):
                event = create_tool_complete_event(
                    stage=self.stage,
                    call_id=str(self.tool_calls),
                    tool_output={"output": str(output)},
                )
                if self.collector:
                    self.collector.on_event(event)

        # Initialize callback
        callback = ObservabilityCallback(self.name, event_collector)

        # Initialize model
        model = ChatAnthropic(
            model=os.environ.get("VERIFLOW_MODEL", "claude-sonnet-4-6"),
            temperature=0.1,
            max_tokens=4096,
            callbacks=[callback],
            streaming=True,
        )

        # Create prompt
        messages = [("human", prompt_content)]
        if system_prompt:
            messages.insert(0, ("system", system_prompt))

        prompt = ChatPromptTemplate.from_messages(messages)

        # Execute with streaming
        try:
            chain = prompt | model
            result_content = chain.invoke({})

            # Extract text content
            output_text = str(result_content.content) if hasattr(result_content, "content") else str(result_content)

            # Send metrics event (estimate tokens)
            input_tokens = self._estimate_tokens(prompt_content)
            output_tokens = self._estimate_tokens(output_text)
            self._last_token_usage = input_tokens + output_tokens

            event = create_metrics_event(
                stage=self.name,
                input_tokens=input_tokens,
                output_tokens=output_tokens,
            )
            if event_collector:
                event_collector.on_event(event)
            yield event

            # Send stream end event
            event = create_stream_end_event(
                stage=self.name,
                success=True,
            )
            if event_collector:
                event_collector.on_event(event)
            yield event

            # Return final result
            result = AgentResult(
                success=True,
                stage=self.name,
                raw_output=output_text,
                metrics={
                    "token_usage": self._last_token_usage,
                    "input_tokens": input_tokens,
                    "output_tokens": output_tokens,
                },
            )
            yield result

        except Exception as e:
            # Send error event
            event = create_error_event(
                stage=self.name,
                error=str(e),
            )
            if event_collector:
                event_collector.on_event(event)
            yield event

            # Send stream end with error
            event = create_stream_end_event(
                stage=self.name,
                success=False,
                error_message=str(e),
            )
            if event_collector:
                event_collector.on_event(event)
            yield event

            raise LLMInvocationError(f"LangChain streaming failed: {e}")

    # === End of Streaming Methods ===
