"""State definitions for VeriFlow LangGraph.

This module defines the TypedDict state structure used by the LangGraph
state machine, including per-stage outputs and execution metadata.
"""

from typing import Annotated, Any, Optional, Sequence, TypedDict
from dataclasses import dataclass, field

from langgraph.graph import add_messages


@dataclass
class StageOutput:
    """Standardized output format for each pipeline stage.

    Attributes:
        success: Whether the stage completed successfully
        artifacts: List of file paths generated by this stage
        metrics: Key performance indicators and measurements
        errors: List of error messages if any
        warnings: List of warning messages
        metadata: Additional stage-specific data
        duration_s: Wall-clock time of this stage in seconds
    """
    success: bool
    artifacts: list[str] = field(default_factory=list)
    metrics: dict[str, Any] = field(default_factory=dict)
    errors: list[str] = field(default_factory=list)
    warnings: list[str] = field(default_factory=list)
    metadata: dict[str, Any] = field(default_factory=dict)
    duration_s: float = 0.0

    def to_dict(self) -> dict[str, Any]:
        """Convert to dictionary for serialization."""
        return {
            "success": self.success,
            "artifacts": self.artifacts,
            "metrics": self.metrics,
            "errors": self.errors,
            "warnings": self.warnings,
            "metadata": self.metadata,
            "duration_s": self.duration_s,
        }

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> "StageOutput":
        """Create from dictionary."""
        return cls(
            success=data.get("success", False),
            artifacts=data.get("artifacts", []),
            metrics=data.get("metrics", {}),
            errors=data.get("errors", []),
            warnings=data.get("warnings", []),
            metadata=data.get("metadata", {}),
            duration_s=data.get("duration_s", 0.0),
        )


class VeriFlowState(TypedDict):
    """Complete state for the VeriFlow LangGraph.

    This state is passed between nodes in the graph and persisted
    across checkpoints for resume capability.

    Attributes:
        # Project Configuration
        project_dir: Root directory of the project
        mode: Pipeline mode (quick/standard/enterprise)

        # Execution State
        current_stage: Name of currently executing stage
        stages_completed: List of successfully completed stages
        stages_failed: List of stages that failed
        retry_count: Per-stage retry attempt counter

        # Stage Outputs
        X_output: StageOutput for each stage X

        # Quality Gates
        quality_gates_passed: Map of gate name to pass/fail

        # Debug/Logging
        messages: Accumulated log messages
    """

    # Project Configuration
    project_dir: str
    mode: str  # "quick" | "standard" | "enterprise"

    # Execution State
    current_stage: str
    stages_completed: Annotated[list[str], lambda x, y: list(set(x + y))]
    stages_failed: list[str]
    retry_count: dict[str, int]

    # Stage Outputs
    architect_output: Optional[StageOutput]
    microarch_output: Optional[StageOutput]
    timing_output: Optional[StageOutput]
    coder_output: Optional[StageOutput]
    skill_d_output: Optional[StageOutput]
    debugger_output: Optional[StageOutput]
    synth_output: Optional[StageOutput]

    # Quality Gates
    quality_gates_passed: dict[str, bool]

    # Debug/Logging
    messages: Annotated[Sequence, add_messages]


def create_initial_state(
    project_dir: str,
    mode: str = "standard",
    resume: bool = False
) -> VeriFlowState:
    """Create initial state for a new pipeline run.

    Args:
        project_dir: Path to the project directory
        mode: Pipeline mode (quick/standard/enterprise)
        resume: Whether to resume from a previous checkpoint

    Returns:
        Initial VeriFlowState with default values
    """
    return VeriFlowState(
        project_dir=project_dir,
        mode=mode,
        current_stage="",
        stages_completed=[],
        stages_failed=[],
        retry_count={
            "architect": 0,
            "microarch": 0,
            "timing": 0,
            "coder": 0,
            "skill_d": 0,
            "sim_loop": 0,
            "synth": 0,
        },
        architect_output=None,
        microarch_output=None,
        timing_output=None,
        coder_output=None,
        skill_d_output=None,
        debugger_output=None,
        synth_output=None,
        quality_gates_passed={},
        messages=[],
    )


def get_mode_stages(mode: str) -> list[str]:
    """Get the list of stages for a given pipeline mode.

    Args:
        mode: Pipeline mode (quick/standard/enterprise)

    Returns:
        List of stage names in execution order
    """
    stages_map = {
        "quick": ["architect", "microarch", "coder", "skill_d"],
        "standard": ["architect", "microarch", "timing", "coder", "skill_d", "sim_loop", "synth"],
        "enterprise": ["architect", "microarch", "timing", "coder", "skill_d", "sim_loop", "synth"],
    }
    return stages_map.get(mode, stages_map["standard"])